<h2>About us</h2>

<p>
Some of us do it to spice up their favorite games, others to familiarize with web developing, and others to improve their photography skills. All of us, without exception, do it for passion.
</p>
<p>
We take <b>screenshots of video games</b> we like and share them here with you all.
<br /> 
Download them, share them, use them as wallpapers for your desktop. You can do what you want with BitGrabbers screenshots, as long as you don't sell them or claim them as your own (and yes, we have the means to know if you will...).
<br />
Just keep in mind that we're not professionals and we don't own supercomputers with ninja hardware... anyway, we compensate the lack of maximum quality with a sense of art and deep passion for video games.
</p>
<p>
Enjoy BitGrabbers and share our screenshots!
</p>

<h2>Contact the Bit Grabbers</h2>
<?php echo $this->form ?>