<h2>Links</h2>
<p>
Every now and then BitGrabbers is linked by other web sites: blogs, online magazines, video games forums. 
<br />
We kindly return the favor by listing here the sites we like.
</p>

<p>
If you want to link to BitGrabbers, please use this html code:
<p>
	Copy and paste this <em>HTML code</em> for a <strong><a href="<?php echo Zend_Registry::get('imagesRelPath') ?>button_120x60.png">120 x 60 button</a></strong>:
</p>
<div class="bannerPre">
	&lt;a href=&quot;http://www.bitgrabbers.com&quot; target=&quot;_blank&quot;&gt; <br />
	&lt;img title=&quot;Videogame screenshots&quot; alt=&quot;BitGrabbers&quot; <br />
	src=&quot;<?php echo Zend_Registry::get('siteBaseUrl') . Zend_Registry::get('imagesRelPath') ?>button_120x60.png&quot; <br />
	width=&quot;120&quot; height=&quot;60&quot; border=&quot;0&quot; /&gt; <br />
	&lt;/a&gt;
</div>
<p>
	Copy and paste this <em>HTML code</em> for a <strong><a href="<?php echo Zend_Registry::get('imagesRelPath') ?>banner_468x60.png">468 x 60 full banner</a></strong>:
</p>
<div class="bannerPre">
	&lt;a href=&quot;http://www.bitgrabbers.com&quot; target=&quot;_blank&quot;&gt; <br />
	&lt;img title=&quot;Videogame screenshots&quot; alt=&quot;BitGrabbers&quot; <br />
	src=&quot;<?php echo Zend_Registry::get('siteBaseUrl') . Zend_Registry::get('imagesRelPath') ?>banner_468x60.png&quot; <br /> 
	width=&quot;468&quot; height=&quot;60&quot; border=&quot;0&quot; /&gt; <br />
	&lt;/a&gt;
</div>


<ul class="links">
	<li>
		<a href="http://www.abandonwaredos.com" title="Abandonware DOS">Abandonware DOS</a>
		Abandonware DOS is a collection of old PC games, no longer on sale nor supported by anyone. Abandonware DOS games are free to download and can be run using a DOS emulator such as DOSBox.
	</li>
	<li>
		<a href="http://www.eveonlineships.com" title="EVE Online Ships">EVE Online Ships</a>
		EVE Online Ships is a screenshots database of ships, stations, planets taken from the MMORPG game EVE Online. The ships database is updated with new screenshots every week.
	</li>
</ul>
