<h2>Tags list</h2>

<?php echo $this->form;?>

<p>
<?php 
	echo '<a href="' . $this->url(array('controller' => 'tag', 'action' => 'create'), 'default', true) . '" title="create">New</a>';
?>
</p>

<table width="935" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <th scope="col" width="80"></th>
        <th scope="col" width="50">Order</th>
        <th scope="col">Tag</th>
    </tr>
    <?php echo $this->partialLoop('tableRows/tagAdmin.phtml', $this->paginator); ?>
</table>

<?php echo $this->paginationControl($this->paginator,
                                            'Sliding',
                                            'partials/pagination-control.phtml'); ?>

