<div id="wrTestata">
	  	<!-- AddThis Button BEGIN -->
		<div class="addthis_toolbox addthis_floating_style addthis_32x32_style" style="left:50px;top:50px;">
			<a class="addthis_button_preferred_1"></a>
			<a class="addthis_button_preferred_2"></a>
			<a class="addthis_button_preferred_3"></a>
			<a class="addthis_button_preferred_4"></a>
			<a class="addthis_button_compact"></a>
		</div>
		<script type="text/javascript">var addthis_config = {"data_track_addressbar":false};</script>
		<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-50e42d8c4aadf5ff"></script>
		<!-- AddThis Button END -->

	<img class="logo" src="<?php echo Zend_Registry::get('imagesRelPath') ?>logo.png" width="283" height="31" alt="Bitgrabbers" title="Bitgrabbers" />
	
	<div class="social">
		<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'rss'), 'rss', true); ?>" title="Subscribe to the Bitgrabbers RSS"><img src="<?php echo Zend_Registry::get('imagesRelPath') ?>rss.png" width="32" height="32" alt="BitGrabbers latest screenshots" /></a>
		<a href="http://bitgrabbers.tumblr.com/" title="The BitGrabbers on tumblr"><img src="<?php echo Zend_Registry::get('imagesRelPath') ?>tumblr.png" width="32" height="32" alt="Tumblr" /></a>
		<a href="http://twitter.com/bitgrabbers" title="The BitGrabbers on Twitter"><img src="<?php echo Zend_Registry::get('imagesRelPath') ?>twitter.png" width="32" height="32" alt="Twitter" /></a>
		<a href="http://www.facebook.com/pages/Bit-Grabbers/331749506929171" title="The BitGrabbers on Facebook"><img src="<?php echo Zend_Registry::get('imagesRelPath') ?>facebook.png" width="32" height="32" alt="Facebook" /></a>
	</div>
</div>