<tr>
	<td><a href="<?php echo $this->friendlyUrl($this->item, 'game'); ?>" title="<?php echo 'See other screenshots for ' . $this->item->name; ?>"><?php echo $this->escape($this->item->name); ?></a></td>
	<td><?php echo $this->escape($this->item->publisher); ?></td>
	<td><?php echo $this->escape($this->item->year); ?></td>
	<td>(<?php echo $this->escape($this->item->getScreenshotsNumber()); ?>)</td>
</tr>