<tr>
	<td>
		<a href='<?php echo $this->url(array('controller' => 'tag', 'action' => 'edit', 'id' => $this->id), 'default', true); ?>'>Edit</a> |
    	<a href='<?php echo $this->url(array('controller' => 'tag', 'action' => 'delete', 'id' => $this->id), 'default', true); ?>' onclick="return confirm('Are you sure you want to delete?')">Del</a>
	</td>
	<td><?php echo $this->escape($this->order); ?></td>
	<td><?php echo $this->escape($this->name); ?></td>
</tr>