<tr>
	<td>
		<a href='<?php echo $this->url(array('controller' => 'user', 'action' => 'edit', 'id' => $this->id), 'default', true); ?>'>Edit</a> |
    	<a href='<?php echo $this->url(array('controller' => 'user', 'action' => 'delete', 'id' => $this->id), 'default', true); ?>' onclick="return confirm('Are you sure you want to delete?')">Del</a> | 
    	<a href='<?php echo $this->url(array('controller' => 'user', 'action' => 'changepwd', 'id' => $this->id), 'default', true); ?>'>Change pwd</a>
	</td>
	<td><?php echo $this->escape($this->username); ?></td>
	<td><?php echo $this->escape($this->role); ?></td>
	<td><?php echo $this->escape($this->email); ?></td>
</tr>