<h2>Screenshots list</h2>


<?php echo $this->form; ?>

<p>
<?php 
	echo '<a href="' . $this->url(array('controller' => 'screenshot', 'action' => 'create'), 'default', true) . '" title="create">New</a>';
?>
</p>

<table width="935" border="0" cellspacing="0" cellpadding="0">
    <tr>
    	<th scope="col" width="160"></th>
        <th scope="col" width="80"></th>
        <th scope="col" width="150">Game</th>
        <th scope="col" width="365">Title</th>
        <th scope="col" width="80">Published</th>
        <th scope="col" width="100">Pub date</th>
    </tr>
    <?php 
    	$this->partialLoop()->setObjectKey('row');
    	echo $this->partialLoop('tableRows/screenshotAdmin.phtml', $this->paginator); 
    ?>
</table>

<?php echo $this->paginationControl($this->paginator,
                                            'Sliding',
                                            'partials/pagination-control.phtml'); ?>


