
  <h1>We can't find your page</h1>
  <p><?php echo $this->message ?></p>
  <p>
  	<img class="logo" 
  		 src="<?php echo Zend_Registry::get('siteBaseUrl') . Zend_Registry::get('imagesRelPath') ?>dead_link.gif" 
  		 alt="Bitgrabbers" 
  		 title="Bitgrabbers" 
  	/>
  </p>

  <?php if(APPLICATION_ENV != 'production') { ?>
  	<?php if (isset($this->exception)): ?>
  
  	<h3>Exception information:</h3>
  	<p>
      	<b>Message:</b> <?php echo $this->exception->getMessage() ?>
  	</p>

  	<h3>Stack trace:</h3>
  	<pre><?php echo $this->exception->getTraceAsString() ?>
  	</pre>

  	<h3>Request Parameters:</h3>
  	<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  	</pre>

  	<?php endif ?>
  <?php } ?>
